version: '3.10'

services:
  audio-miner:
    build: .
    container_name: audio_mining_bot
    volumes:
      - my_audio_storage:/app/output 
      - ./data:/app/data
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: unless-stopped

volumes:
  my_audio_storage: